name: Update Commit Score

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Ejecuta diariamente

jobs:
  calculate-score:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate commit score
        id: score
        run: |
          SCORE=$(git log --pretty=format:"%H" | wc -l)
          SCORE=$((SCORE % 100))
          echo "commit_score=$SCORE" >> $GITHUB_ENV

      - name: Create Badge
        uses: mikepenz/github-action-badge@v1.5.1
        with:
          label: 'Commit Score'
          message: ${{ env.commit_score }}
          color: green

      - name: Push badge to repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add badges/commit-score.svg
          git commit -m "Update commit score badge"
          git push
